import NavbarComponent from "@/components/NavbarComponent";
import "../globals.css";
import SidebarComponent from "@/components/SidebarComponent";
import ListBoardComponentHeader from "@/components/ListBoardComponentHeader";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className="font-SFProDisplay w-fit">
                {/* <div className="">
                    <div className="w-full flex">
                        <SidebarComponent />
                        <NavbarComponent />

                        <div>
                            <ListBoardComponentHeader />
                        </div>
                    </div>
                </div> */}
                <div className="grid grid-cols-12">
                    <div className="col-span-2">
                        <SidebarComponent />
                    </div>
                    <div className="col-span-10 m-10">
                        <div>
                            <NavbarComponent />
                        </div>
                        <div>
                            <ListBoardComponentHeader />
                        </div>
                        <div>
                            {children}
                        </div>
                    </div>
                </div>

            </body>
        </html>
    );
}